---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      day: friday
      time: "05:00"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "chore(github-actions): "

  - package-ecosystem: nuget
    directory: "/"
    groups:
      microsoft:
        patterns:
          - Microsoft*
        update-types: ["minor", "patch"]
      testing:
        patterns:
          - AutoFixture*
          - coverlet*
          - FluentAssertions*
          - GitHubActionsTestLogger
          - xunit*
        update-types: ["minor", "patch"]
    schedule:
      interval: weekly
      day: friday
      time: "05:00"
      timezone: "Australia/Perth"
    commit-message:
      prefix: "dependencies(nuget): "
