add-missing-labels: true # Whether to add missing labels to the repository
clear-prexisting: true # Whether to remove prexisting labels from the PR in favour of the generated one
include-commits: false # Consider the PR commit messages when adding labels
include-title: true # Consider the PR title when adding labels
label-for-breaking-changes: 'breaking' # Label to be used when the message has the breaking change syntax '!:' E.g. "feat!: This break things"
label-mapping:
  breaking: [ 'breaking', 'BREAKING CHANGE', 'breaking change', 'breaking changes' ]
  bug: [ 'fix' ]
  documentation: [ 'docs' ]
  feature: [ 'feat', 'feature' ]
  misc: [ 'perf', 'refactor', 'revert', 'style', 'test' ]
  no-release: [ 'build', 'chore', 'ci', 'dependencies' ]

