name: dotnet-build-and-package

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      dotnet-version:
        required: true
        type: string
      package-version:
        required: true
        type: string
      assembly-version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  dotnet-build-and-package:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install .NET Core ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Restore packages
        run: dotnet restore

      - name: Package
        run: >
          dotnet pack
          --no-restore
          --configuration Release
          --output build-pacakges
          /p:Version=${{ inputs.package-version }}
          /p:FileVersion=${{ inputs.assembly-version }}
          /p:AssemblyVersion=${{ inputs.assembly-version }}
          /p:AssemblyInformationalVersion=${{ inputs.assembly-version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pacakges
          path: build-pacakges/*.nupkg
          if-no-files-found: error
