name: version

on:
  workflow_call:
    inputs:
      version-artifact-name:
        description: "Name of the artifact to put the version file in"
        required: false
        type: string
        default: "version"
    outputs:
      version:
        description: The new version number
        value: ${{ jobs.find-version.outputs.version }}
      current-version:
        description: The current version number
        value: ${{ jobs.find-version.outputs.current-version }}

permissions:
  contents: read

jobs:
  find-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      current-version: ${{ steps.get-version.outputs.current-version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get version
        uses: reecetech/version-increment@a5d65984a6c6e8bbc30ece69d53d96e40736f24c # 2024.9.2
        id: get-version
        with:
          scheme: conventional_commits
          increment: patch

      - name: Current version
        run: echo "${{ steps.get-version.outputs.current-version }}"

      - name: New version
        id: write_version
        run: |
          VERSION="${{ steps.get-version.outputs.version }}"
          echo "New version: $VERSION"
          echo $VERSION > version.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: ${{ inputs.version-artifact-name }}
          path: version.txt
          if-no-files-found: error
