name: ci-cd

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Directory.*.props"

permissions:
  contents: read

jobs:
  ci-cd:
    permissions:
      contents: write
      packages: write
    uses: saan800/github/.github/workflows/_dotnet-build-test-package-publish.yml@main
    with:
      os-list: "ubuntu-latest, windows-latest"
      os: ubuntu-latest
      dotnet-version-list: "6.0.x, 7.0.x, 8.0.x"
      dotnet-version: 8.0.x
      codecov-slug: "saan800/saansoft-correlationId"
      is-release: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}
