name: ci

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "src/**"

permissions:
  contents: read

jobs:
  build-and-test:
    permissions:
      contents: read
      checks: write

    uses: ./.github/workflows/_dotnet-build-and-test.yml
    with:
      os-list: "ubuntu-latest, windows-latest"
      dotnet-version-list: "6.0.x, 7.0.x, 8.0.x"
      codecov-slug: "saan800/saansoft-correlationId"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  find-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      assembly-version: ${{ steps.get-assembly-version.outputs.assembly-version }}
      current-version: ${{ steps.get-version.outputs.current-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get next version
        uses: reecetech/version-increment@a5d65984a6c6e8bbc30ece69d53d96e40736f24c # 2024.9.2
        id: get-version
        with:
          scheme: conventional_commits
          increment: patch

      - name: Modify version and set assembly version
        id: get-assembly-version
        run: |
          # Capture the version output from previous step
          version="${{ steps.get-version.outputs.version }}"

          # Replace '-pre' with ''
          modified_version=$(echo "$version" | sed 's/-pre//')

          # Set the modified version as output
          echo "::set-output name=assembly-version::$modified_version"

      - name: display current version
        run: echo "${{ steps.get-version.outputs.current-version }}"

      - name: display new version
        run: echo "${{ steps.get-version.outputs.version }}"

      - name: display new assembly version
        run: echo "${{ steps.get-assembly-version.outputs.assembly-version }}"

  build-and-package:
    needs:
      - build-and-test
      - find-version
    uses: ./.github/workflows/_dotnet-build-and-package.yml
    with:
      os: ubuntu-latest
      dotnet-version: 8.0.x
      package-version: ${{ needs.find-version.outputs.version }}
