name: ci

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "src/**"

permissions:
  contents: read

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      os_array: ${{ steps.generate-matrix.outputs.os_array }}
      version_array: ${{ steps.generate-matrix.outputs.version_array }}

    env:
      OS_LIST: "ubuntu-latest,windows-latest"
      VERSION_LIST: "6.0.x, 7.0.x,8.0.x"

    steps:
      - name: Generate Matrix Variables
        id: generate-matrix
        run: |
          tempOsList=${{ env.OS_LIST }}
          echo "os_array=[\"${tempOsList//','/\",\"}\"]" >> $GITHUB_OUTPUT

          tempVersionList="${{ env.VERSION_LIST }}"
          tempVersionList="${tempVersionList//', '/','}"
          echo "version_array=[\"${tempVersionList//','/\",\"}\"]" >> $GITHUB_OUTPUT

      - name: Show Matrix Variables
        run: |
          echo "os_array=${{ steps.generate-matrix.outputs.os_array }}"
          echo "version_array=${{ steps.generate-matrix.outputs.version_array }}"

  build-and-test:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        os: ${{fromJson(needs.generate-matrix.outputs.os_array)}}
        dotnet-version: ${{fromJson(needs.generate-matrix.outputs.version_array)}}

    permissions:
      contents: read
      checks: write

    uses: ./.github/workflows/_dotnet-build-and-test.yml
    with:
      os: ${{ matrix.os }}
      dotnet-version: ${{ matrix.dotnet-version }}
      codecov-slug: "saan800/saansoft-correlationId"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  version:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get next version
        uses: reecetech/version-increment@dee3ec8905aa206545f928256a2cc2125c5fb2f5 # 2024.4.3
        id: version
        with:
          scheme: conventional_commits
          increment: patch

      - name: display current version
        run: echo "${{ steps.version.outputs.current-version }}"

      - name: display new version
        run: echo "${{ steps.version.outputs.version }}"

      # - name: Set outputs
      #   id: set_outputs
      #   run: echo "::set-output name=version::${{ steps.version.outputs.version }}"
