name: ci

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Directory.*.props"

permissions:
  contents: read

jobs:
  build-and-test:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/_dotnet-build-and-test.yml
    with:
      os-list: "ubuntu-latest, windows-latest"
      dotnet-version-list: "6.0.x, 7.0.x, 8.0.x"
      codecov-slug: "saan800/saansoft-correlationId"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  get-version:
    uses: ./.github/workflows/_version.yml

  build-and-package:
    needs:
      - build-and-test
      - get-version
    uses: ./.github/workflows/_dotnet-build-and-package.yml
    with:
      os: ubuntu-latest
      dotnet-version: 8.0.x
      package-version: ${{ needs.get-version.outputs.version }}
      add-assembly-version: ${{ github.ref == 'refs/heads/main' }}
