name: pr

on:
  pull_request:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-labels:
    permissions:
      contents: read
      pull-requests: write
    uses: saan800/github/.github/workflows/pr-labeler.yml@main
    secrets:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
