name: pr

on:
  pull_request:

permissions:
  actions: read
  contents: write
  packages: write
  pull-requests: write
  security-events: write

jobs:
  dotnet-package-pr:
    permissions:
      actions: read
      contents: write
      packages: write
      pull-requests: write
      security-events: write
    uses: saan800/github/.github/workflows/dotnet-package-pr.yml@main
    with:
      os: ubuntu-latest
      dotnet-version: 9.0.x
      codecov-slug: "saan800/saansoft-correlationId"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
