name: pr

on:
  pull_request:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  dotnet-package-pr:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    uses: saan800/github/.github/workflows/dotnet-package-pr.yml@main
    with:
      os: ubuntu-latest
      dotnet-version: 9.0.x
      run-lint: true
      cspell-config: ".cspell.json"
      codecov-slug: "saan800/saansoft-correlationId"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
