name: pr

on:
  pull_request:

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  dotnet-package-pr:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/dotnet-package-pr.yml
    with:
      os: ubuntu-latest
      dotnet-version: 9.0.x
      codecov-slug: "saan800/saansoft-correlationId"
      is-release-branch: ${{ github.ref == 'refs/heads/main' }}
      force-release: ${{ github.event.inputs.force-release == 'true' }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
